apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf  
data:
  host: mysqlsrv  # mysql DNS of Service
  name: users-db 
  url: jdbc:mysql://mysqlsrv:3306/users-db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
---
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials 
data:
  password: cm9vdDEyMw== # base64 encoded root123 password
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
  username: c2hwYm9yaXM=  # base64 encoded shpboris username
  password: cGFzczEyMw== # base64 encoded pass123 password
