apiVersion: v1
kind: Service
metadata:
  name: usersrestsrv 
  labels:
    app: usersapp
    component: restserver
spec:
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
    nodePort: 30080
  selector:  # pod lables should match these
    app: usersapp
    component: restserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restserver
  labels: 
    app: usersapp
    component: restserver
spec:
  replicas: 1   
  selector:
    matchLabels: # pod labels should match these
      app: usersapp
      component: restserver
  template:
    metadata:
      labels: # Must macth 'Service' and 'Deployment' labels
        app: usersapp
        component: restserver  
    spec:                 
      containers: 
      - name: usersrestserver 
        image: shpboris/usersrestserver
        env:   
          - name: MYSQL_URL
            valueFrom: 
              configMapKeyRef:
                name: db-conf
                key: url
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password     
        ports:
        - containerPort: 8000